# Raw data to clean data conversion using python EDA

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
emp = pd.read_excel(r"C:\Users\DELL\Downloads\Rawdata.xlsx")

In [4]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [5]:
id(emp)

2514077772368

In [6]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [7]:
emp.shape

(6, 6)

In [8]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [9]:
emp.tail()

     Name          Domain     Age   Location   Salary      Exp
1  Teddy^         Testing  45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#     NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics     NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67-yr        NaN   30000-  5+ year
5     Kim             NLP    55yr      Delhi  6000^$0      10+

In [10]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [11]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [12]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [13]:
emp.isna()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [14]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

# DATA CLEANING OR DATA CLEANSING

In [15]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [16]:
emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [17]:
emp['Name'] = emp['Name'].str.replace(r'\W','',regex=True) #Non Word charac

In [18]:
emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: object

In [19]:
emp['Domain']

0     Datascience#$
1           Testing
2    Dataanalyst^^#
3       Ana^^lytics
4        Statistics
5               NLP
Name: Domain, dtype: object

In [20]:
 emp['Domain'] = emp['Domain'].str.replace(r'\W','',regex=True) #Non Word charac

In [21]:
emp['Domain']

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: object

In [22]:
emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [52]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [53]:
emp['Age'] = emp['Age'].str.replace(r'\W','',regex=True) #Non Word charac

In [54]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [55]:
emp['Age'] = emp['Age'].str.extract('(\\d+)') #Non Word charac

In [56]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [57]:
emp

    Name       Domain  Age   Location Salary    Exp
0   Mike  Datascience   34     Mumbai      5      2
1  Teddy      Testing   45  Bangalore     10      3
2   Umar  Dataanalyst  NaN        NaN      1   4yrs
3   Jane    Analytics  NaN   Hyderbad   2000    NaN
4  Uttam   Statistics   67        NaN  30000  5year
5    Kim          NLP   55      Delhi   6000     10

In [58]:
emp['Location'] = emp['Location'].str.replace(r'\W','',regex=True) #Non Word charac

In [59]:
emp['Location']

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [60]:
emp['Salary']

0        5
1       10
2        1
3     2000
4    30000
5     6000
Name: Salary, dtype: object

In [61]:
emp['Salary'] = emp['Salary'].str.extract('(\\d+)') #Non Word charac

In [62]:
emp['Salary']

0        5
1       10
2        1
3     2000
4    30000
5     6000
Name: Salary, dtype: object

In [63]:
emp

    Name       Domain  Age   Location Salary    Exp
0   Mike  Datascience   34     Mumbai      5      2
1  Teddy      Testing   45  Bangalore     10      3
2   Umar  Dataanalyst  NaN        NaN      1   4yrs
3   Jane    Analytics  NaN   Hyderbad   2000    NaN
4  Uttam   Statistics   67        NaN  30000  5year
5    Kim          NLP   55      Delhi   6000     10

In [64]:
emp['Exp']

0        2
1        3
2     4yrs
3      NaN
4    5year
5       10
Name: Exp, dtype: object

In [67]:
emp['Exp'] = emp['Exp'].str.extract('(\\d+)') #Non Word charac

In [68]:
emp['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: object

In [69]:
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai      5    2
1  Teddy      Testing   45  Bangalore     10    3
2   Umar  Dataanalyst  NaN        NaN      1    4
3   Jane    Analytics  NaN   Hyderbad   2000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi   6000   10

In [70]:
clean_data = emp.copy()

In [71]:
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai      5    2
1  Teddy      Testing   45  Bangalore     10    3
2   Umar  Dataanalyst  NaN        NaN      1    4
3   Jane    Analytics  NaN   Hyderbad   2000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi   6000   10

# EDA TECHNIQUE

* missing values treatment

In [72]:
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai      5    2
1  Teddy      Testing   45  Bangalore     10    3
2   Umar  Dataanalyst  NaN        NaN      1    4
3   Jane    Analytics  NaN   Hyderbad   2000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi   6000   10

In [73]:
clean_data.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [74]:
clean_data['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [75]:
import numpy as np

In [76]:
clean_data['Age'] = clean_data['Age'].fillna(np.mean(pd.to_numeric(clean_data['Age'])))

In [77]:
clean_data['Age']

0       34
1       45
2    50.25
3    50.25
4       67
5       55
Name: Age, dtype: object

In [78]:
clean_data['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: object

In [79]:
clean_data['Exp'] = clean_data['Exp'].fillna(np.mean(pd.to_numeric(clean_data['Exp'])))

In [80]:
clean_data['Exp']

0      2
1      3
2      4
3    4.8
4      5
5     10
Name: Exp, dtype: object

In [81]:
clean_data

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai      5    2
1  Teddy      Testing     45  Bangalore     10    3
2   Umar  Dataanalyst  50.25        NaN      1    4
3   Jane    Analytics  50.25   Hyderbad   2000  4.8
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi   6000   10

In [82]:
clean_data['Location'].isnull().sum()

np.int64(2)

In [83]:
clean_data['Location']

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [84]:
clean_data['Location'] = clean_data['Location'].fillna(clean_data['Location'].mode()[0])

In [85]:
clean_data['Location']

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: object

In [86]:
clean_data

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai      5    2
1  Teddy      Testing     45  Bangalore     10    3
2   Umar  Dataanalyst  50.25  Bangalore      1    4
3   Jane    Analytics  50.25   Hyderbad   2000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi   6000   10

In [87]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      object
 3   Location  6 non-null      object
 4   Salary    6 non-null      object
 5   Exp       6 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [88]:
clean_data['Age'] = clean_data['Age'].astype(int)

In [89]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      int64
 3   Location  6 non-null      object
 4   Salary    6 non-null      object
 5   Exp       6 non-null      object
dtypes: int64(1), object(5)
memory usage: 420.0+ bytes

In [90]:
clean_data['Salary'] = clean_data['Salary'].astype(int)

In [92]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      int64
 3   Location  6 non-null      object
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      object
dtypes: int64(2), object(4)
memory usage: 420.0+ bytes

In [93]:
clean_data['Exp'] = clean_data['Exp'].astype(int)

In [95]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      int64
 3   Location  6 non-null      object
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: int64(3), object(3)
memory usage: 420.0+ bytes

In [97]:
clean_data['Name'] = clean_data['Name'].astype('category')
clean_data['Domain'] = clean_data['Domain'].astype('category')
clean_data['Location'] = clean_data['Location'].astype('category')

In [98]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int64
 3   Location  6 non-null      category
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: category(3), int64(3)
memory usage: 938.0 bytes

In [99]:
clean_data

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai       5    2
1  Teddy      Testing   45  Bangalore      10    3
2   Umar  Dataanalyst   50  Bangalore       1    4
3   Jane    Analytics   50   Hyderbad    2000    4
4  Uttam   Statistics   67  Bangalore   30000    5
5    Kim          NLP   55      Delhi    6000   10

In [100]:
clean_data.to_csv('clean_data.csv')

In [102]:
import os
os.getcwd() # to save file in the systemand this is the location where it is saved

'C:\\Users\\DELL'

In [103]:
clean_data

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai       5    2
1  Teddy      Testing   45  Bangalore      10    3
2   Umar  Dataanalyst   50  Bangalore       1    4
3   Jane    Analytics   50   Hyderbad    2000    4
4  Uttam   Statistics   67  Bangalore   30000    5
5    Kim          NLP   55      Delhi    6000   10